import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";

const Home: NextPage = () => {
  return (
    <div className="p-4 flex gap-4 flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl font-bold underline">Hello World</div>
      <Button>Primary</Button>
      <Button variant="secondary">Secondary</Button>
      <Button variant="regular">Regular</Button>
    </div>
  );
};

export default Home;
