import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";
import { FaBeer } from "react-icons/fa";

const Home: NextPage = () => {
  return (
    <div className="p-4 flex gap-4 flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button Icon={FaBeer}>Primary</Button>
      <Button Icon={FaBeer} variant="secondary">
        Secondary
      </Button>
      <Button Icon={FaBeer} variant="regular">
        Regular
      </Button>
    </div>
  );
};

export default Home;
